---
- name: "Installing apache webserver"
  hosts: 192.168.0.219 #server b
  become: yes
  tasks:
    - name: Install Apache
      yum: 
        name: httpd
        state: installed
    - name: Udate all packages on the web server
      yum: 
        name: '*'
        state: latest
      
    - name: Add index.html file
      copy:
        dest: /var/www/html/index.html
        content: "Hello From the Ansible Challenge"
      notify:
        - Restart Apache 
    
    - name: Add firewall rule
      firewalld:
        state: enabled
        service: http
        permanent: yes
        immediate: yes
  
  
  handlers:   
    - name: Restart Apache
      service:
        state: started
        name: httpd
        enabled: yes
  
            
       
        